# config/redis.yml
default: &default
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/0") %>
  timeout: 5
  reconnect_attempts: 3
  reconnect_delay: 0.5
  reconnect_delay_max: 2.0

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/1") %>

production:
  <<: *default
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/0") %>
